# Generated by Django 4.1.3 on 2025-03-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_menu_description'),
    ]

    operations = [
       migrations.AddField(
    model_name='menu',
    name='description',
    field=models.TextField(max_length=1000, default="Default description"),
),

    ]
